# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bigcategory_name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
