# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_bigcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specify',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
    ]
