# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180325_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigcategory',
            old_name='title',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
    ]
