# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180325_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specify',
            name='image',
            field=models.ImageField(default='image/None/no-img.jpg', null='false', upload_to='image'),
        ),
    ]
